### PR TITLE
feat: support prefixes for nested structs

### PR DESCRIPTION
**Pull request by bunyk**
A first draft implementation of #52, names of struct fields are considered now.

### CODE REVIEW

**Review by tmzane — CHANGES_REQUESTED** [review]

**Comment by bunyk** [comment]
I'll check the coverage later today

**Comment by tmzane** [comment]
> I'll check the coverage later today

Don't bother, looks like this is about changes in the coverage tool. I'll take a look later.

**Comment by tmzane** [comment]
I'm going to push documentation updates and then we can merge it.

**Review by tmzane — APPROVED** [review]

**Comment by tmzane** [comment]
@bunyk thank you for the contribution!

**Pull request merged**
